### ISSUE TITLE
Build failure with newest haskell-src-exts

### ISSUE THREAD

**Issue by snoyberg** [lambdabot/lambdabot#139] opened 2015-12-09 14:54 UTC
Full build log at: https://gist.github.com/snoyberg/e067c0e9ccb6dc43f4d9

**Comment by snoyberg** [comment] 2015-12-09 15:40
Pinging @DanBurton, the Stackage maintainer.

**Comment by DanBurton** [comment] 2015-12-09 18:59
I'm inclined to remove lambdabot from stackage. Feel free to comment it out if it becomes the last one holding back haskell-src-exts.

**Comment by snoyberg** [comment] 2015-12-09 18:59
I've already commented it out actually.

**Comment by nomeata** [comment] 2016-04-27 07:19
Affecting Debian as well. Also inclined to remove it.

**Comment by int-e** [comment] 2016-05-16 19:16
(the original bug is a duplicate of #138)

As for the discussion here, sorry, but I tend to do only maintenance when a new ghc release turns up.

**Closed by int-e** 2016-05-16 19:16 UTC
