### ISSUE TITLE
Doesn't compile with GHC 7.8.3 (roles)

### ISSUE THREAD

**Issue by Fuuzetsu** [lambdabot/lambdabot#84] opened 2014-08-10 22:14 UTC
```
src/Lambdabot/Monad.hs-boot:4:1:
    Type constructor ‘LB’ has conflicting definitions in the module
    and its hs-boot file
    Main module: type role LB nominal
                 newtype LB a
                   = LB {runLB :: ReaderT (IRCRState, IORef IRCRWState) IO a}
    Boot file:   data LB a
```

http://hydra.cryp.to/build/164390/log/raw

**Comment by ocramz** [comment] 2015-01-08 13:22
I can confirm, doesn't build on GHCi 7.8.3., due to the same type mismatch

**Comment by int-e** [comment] 2015-01-10 09:04
This was fixed by #78, but has not been released to hackage yet.

**Comment by int-e** [comment] 2015-02-23 00:20
The fix is now on hackage.

**Closed by int-e** 2015-02-23 00:20 UTC
